resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
#git resource for the Pipelines
- name: offline-resources-repo
  type: git
  source:
    uri: https://github.com/ahocking/download-offline-resources
    branch: mling

jobs:
- name: DOWNLOAD-OPSMAN
  plan: 
  - get: offline-resources-repo
  - task: download-opsman
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{opsmman_produt_slug}}
      TARGET_VERSION: {{opsmman_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-ERT
  plan: 
  - get: offline-resources-repo
  - task: download-ert
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{ert_produt_slug}}
      TARGET_VERSION: {{ert_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}
      SRT: {{small_runtime_ert}}

- name: DOWNLOAD-P-REDIS
  plan: 
  - get: offline-resources-repo
  - task: download-redis
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{redis_produt_slug}}
      TARGET_VERSION: {{redis_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-P-RABBITMQ
  plan: 
  - get: offline-resources-repo
  - task: download-rabbit
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{rabbitmq_produt_slug}}
      TARGET_VERSION: {{rabbitmq_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-SPRING-CLOUD-SERVICES
  plan: 
  - get: offline-resources-repo
  - task: download-scs
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{scs_produt_slug}}
      TARGET_VERSION: {{scs_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-METRICS
  plan: 
  - get: offline-resources-repo
  - task: download-metrics
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{metrics_produt_slug}}
      TARGET_VERSION: {{metrics_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-P-SCHEDULER
  plan: 
  - get: offline-resources-repo
  - task: download-scheduler
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{scheduler_produt_slug}}
      TARGET_VERSION: {{scheduler_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-P-DATAFLOW
  plan: 
  - get: offline-resources-repo
  - task: download-dataflow
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{dataflow_produt_slug}}
      TARGET_VERSION: {{dataflow_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-P-CLOUDCACHE
  plan: 
  - get: offline-resources-repo
  - task: download-cloudcache
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{cloudcache_produt_slug}}
      TARGET_VERSION: {{cloudcache_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}
  

- name: DOWNLOAD-CREDHUB-SERVICE-BROKER
  plan: 
  - get: offline-resources-repo
  - task: download-credhub-service-broker
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{credhub-service-broker_produt_slug}}
      TARGET_VERSION: {{credhub-service-broker_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-HARBOR
  plan: 
  - get: offline-resources-repo
  - task: download-harbor
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{harbor_produt_slug}}
      TARGET_VERSION: {{harbor_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-CONCOURSE
  plan: 
  - get: offline-resources-repo
  - task: download-concourse
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{concourse_produt_slug}}
      TARGET_VERSION: {{concourse_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}