resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
#git resource for the Pipelines
- name: offline-resources-repo
  type: git
  source:
    uri: https://github.com/ahocking/download-offline-resources
    branch: mling

jobs:
- name: DOWNLOAD-OPSMAN
  plan: 
  - get: offline-resources-repo
  - task: download-opsman
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{opsmman_produt_slug}}
      TARGET_VERSION: {{opsmman_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-ERT
  plan: 
  - get: offline-resources-repo
  - task: download-ert
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{ert_produt_slug}}
      TARGET_VERSION: {{ert_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}

- name: DOWNLOAD-P-REDIS
  plan: 
  - get: offline-resources-repo
  - task: download-redis
    file: offline-resources-repo/tasks/download-pivnet-products/task.yml
    params:
      PRODUCT_SLUG: {{redis_produt_slug}}
      TARGET_VERSION: {{redis_target_version}}
      REVISIONS: {{revisions}}
      IAAS_TYPE: {{iaas_type}}
      API_TOKEN: {{pivnet_token}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      S3_BUCKET_NAME: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}
