pivnet_token: CHANGEME
s3_access_key_id: CHANGEME
s3_secret_access_key: CHANGEME
s3_endpoint: CHANGEME
s3_bucket: CHANGEME

opsman_major_minor_version_2_1: ^2\.1\.2$
ert_major_minor_version_2_1: ^2\.1\.2$
opsman_major_minor_version_2_0: ^2\.0\.11$
ert_major_minor_version_2_0: ^2\.0\.11$
stemcell_version: 3363\.53$


isolation_segment_major_minor_version: ^2\.1\.1$
redis_major_minor_version: ^1\.11\.3$
rabbitmq_major_minor_version: ^1\.11\.12$
spring_cloud_services_major_minor_version: ^1\.5\.2$
mysql_major_minor_version: ^1\.10\.13$
mysqlv2_major_minor_version: ^2\.2\.4$
healthwatch_major_minor_version: ^1\.1\.6$
dataflow_major_minor_version: ^1\.0\.1$
single_sign_on_major_minor_version: ^1\.5\.3$
minio_major_minor_version: ^1\.0\.0$
credhub-service-broker_major_minor_version: ^1\.0\.0$
mongodb-enterprise-service_major_minor_version: ^1\.0\.3$
crunchy-postgresql_major_minor_version: ^03\.090512\.109$